### ISSUE TITLE
Generating mask in training

### ISSUE THREAD

**Issue by ksai2324** [lorenzo-stacchio/Stable-Diffusion-Inpaint#4]
Hello,
 
first of all thanks for the great work!

I was going through your work and what I find missing is how the masks are generated. I'm asking because according to the latent diffusion paper, they used a similar approach as in [LaMa](https://github.com/advimman/lama), in which for the training, parts of the image are randomly taking out and used as masks. My question is when you generated the masks for training did you do that randomly or did you chose masks of specific objects? 

Thanks in advance!

**Comment by lorenzo-stacchio** [comment]
Hello, 

thanks for appreciating!

Yes that's correct, in this case I just provided a simple method to fine-tune stable diffusion having already the mask generated (in a custom way). 

However, I have also implemented llama mask generation for my dataset and i will soon upload this feature in the repo. 

Meanwhile, you could easily integrate it referring to the [yaml configuration file](https://github.com/advimman/lama/blob/7dee0e4a3cf5f73f86a820674bf471454f52b74f/configs/data_gen/random_medium_512.yaml#L4) and the main generating script (https://github.com/advimman/lama/blob/7dee0e4a3cf5f73f86a820674bf471454f52b74f/bin/gen_mask_dataset.py). I will close this issue when i will be able to test and integrate here :)
